config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index', as: :dashboards
  get 'posts/:id', to: 'posts#show'
  resources :logins, only: [:new, :create]
  resources :registrations, only: [:new, :create]
  resources :posts, only: [:new, :create, :update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
    @posts = Post.all
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)

    if @user 
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Email or password was invalid"
      render :new, status: :unprocessable_entity
    end 
  end

  private 

    def login_params
      params.require(:user).permit(:email, :password)
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    user = User.find_by(id: session[:user_id])
    @post = user.posts.new(post_params)

    if @post.save
      flash[:notice] = "Post was successfully created."
      redirect_to dashboards_path
    else
      flash[:alert] = "Unable to save post."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end 

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to dashboards_path
    else
      flash[:alert] = "Post could not be updated"
      render :new, status: :unprocessable_entity
    end 
  end

  private 

    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end 

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to new_login_path
    else 
      flash[:alert] = "Couldn't save the user."
      render :new, status: :unprocessable_entity
    end 
  end


  private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome!</h1>


<% @posts.each do |post| %>
  <ul>
    <li><%= link_to post.title, post_path(post) %></li>
    <li><%= post.body %></li>
  </ul>
<% end %> 

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div><%= notice %></div>
    <div><%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log In</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Log In" %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_with model: @post, url: post_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit "Edit Post" %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= form_for(@post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1>Posts</h1>

<h4><%= @post.title %></h4>

<p><%= @post.body %></p>

<% if session[:user_id] == @post.user_id %>
  <%= link_to "Edit", edit_post_path(@post) %> 
  <%= link_to "Create New Post", new_post_path %>
<% end %>